#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS pg_trgm;
    CREATE EXTENSION IF NOT EXISTS unaccent;

    CREATE ROLE horus_ingest LOGIN PASSWORD '$HORUS_INGEST_PASSWORD';
    CREATE ROLE horus_screen LOGIN PASSWORD '$HORUS_SCREEN_PASSWORD';
    CREATE ROLE horus_audit LOGIN PASSWORD '$HORUS_AUDIT_PASSWORD';
EOSQL
